### ISSUE TITLE
Datasets not rendering when logged in.

### ISSUE THREAD

**Issue by henri-egger** [noi-techpark/it.bz.opendatahub.databrowser#111]
After making a brand new account (Registered and verified E-mail), when entering any dataset it suddenly doesn't render anymore but instead only shows: **ERROR {}**. The console logs:

```console
--------ERROR CAPTURED TypeError: Cannot read properties of undefined (reading 'includes')
    at Proxy.<anonymous> (index.a2eed0a1.js:48:55729)
    at index.a2eed0a1.js:48:55794
    at Array.find (<anonymous>)
    at Proxy.<anonymous> (index.a2eed0a1.js:48:55781)
    at Proxy.hasCreatePermission (index.a2eed0a1.js:105:55771)
    at Bf.fn (index.a2eed0a1.js:9:1311)
    at Bf.run (index.a2eed0a1.js:2:16276)
    at get value [as value] (index.a2eed0a1.js:2:24761)
    at Object.get (index.a2eed0a1.js:2:18627)
    at Bf.fn (DatasetPage.dd077f2d.js:3:17612)

TypeError: Cannot read properties of undefined (reading 'includes')
    at Proxy.<anonymous> (index.a2eed0a1.js:48:55729)
    at index.a2eed0a1.js:48:55794
    at Array.find (<anonymous>)
    at Proxy.<anonymous> (index.a2eed0a1.js:48:55781)
    at Proxy.hasCreatePermission (index.a2eed0a1.js:105:55771)
    at Bf.fn (index.a2eed0a1.js:9:1311)
    at Bf.run (index.a2eed0a1.js:2:16276)
    at get value [as value] (index.a2eed0a1.js:2:24761)
    at Object.get (index.a2eed0a1.js:2:18627)
    at Bf.fn (DatasetPage.dd077f2d.js:3:17612)
```

**Comment by gappc** [comment]
Hi @henri-egger, thank you for reporting the problem. This seem to be indeed a bug and in addition points at a weak part of the current Databrowser implementation: error reporting

Some questions:
- does it work when you are not logged in?
- what browser / OS did you use?
- do you have ad-blockers (similar) stuff running?
- did you use the code from the development branch or did you make some changes?
- could you please provide an example URL that we can copy/paste to see if it "works on my machine"?

More advanced (don't worry if you don't now what the next few lines mean):
- could you take a look at the Bearer token in the Authorization Header for requests that hit the ODH API and check what roles it contains (you can use https://jwt.io/ for decoding)? -> PLEASE **DO NOT** POST A BEARER TOKEN INTO THIS THREAD!!!

As an alternative:
- we could do a quick meeting to see where the problem is
- ask @RudiThoeni if he knows whats going on, maybe some roles are missing

**Comment by henri-egger** [comment]
Thank you for the quick response, about the questions:

- Yes it does work when i am not logged in.
- I am using the Chrome browser with windows 11.
- Yes i do use an adblocker, howerver the problem persists, even when deactivating it.
- The problem occurrs on Testingmachine as well as on my Localhost (With changes and without).
- Follow [this](https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Accommodation) url and log with a newly created account.

Regarding the Bearer token (Discussed this with Rudi):
- When creating a new account, it initially includes no roles (Not even the field). However Rudi programmed the API to handle this case and give back the reduced, open data. So the data not arriving is not the problem, However we thought there might be some kind of check for this field which results in an error due to the field not existing.
- Then we did a test with the most basic read persmission granted, which results in the same data as open data. There it worked. Rudi said he would also be able to assign this role by default, which would eliminate the problem, however first we thought it would be best to find the problem in the client side application.

If you can't replicate the error yourself, we can also do a quick meeting. I am available all day.

**Comment by gappc** [comment]
Hi @henri-egger: well done :) Could you please provide a pull request?

**Comment by henri-egger** [comment]
@gappc Pull request opened and ready for review.
