### ISSUE TITLE
Message box

### ISSUE THREAD

**Issue by mrabans** [noi-techpark/it.bz.opendatahub.databrowser#159]
In order to show messages, warnings and errors we need a place to put such information.

This could be the toolbox with a dedicated tab.

Use cases would be:
- Error messages from the API i.e. validation errors, etc
- Information on endpoints, i.e. "this endpoint is deprecated"
- Additional information on realtime data i.e. latency, etc.

**Comment by gappc** [comment]
Hi @mrabans, I'm not sure if the toolbox is the right place to show messages, warnings, ... I see some problems:

- the toolbox may not always be visible, e.g. the quick-view seems to have no toolbox at all (at least as of https://www.figma.com/file/FAFLmL1P65CnUmb0CYBiGo/MVP2?node-id=144%3A5573). Also, other content pages (home, dataset list, ...) don't have a toolbox at all
- the toolbox in the mobile view is an overlay. That means that there would be no user-friendly way to show messages/errors to the user without disturbing it with the overlay
- if a toolbox provides several tabs, we would need to jump to the message/error tab each time something happens. For me as a user, that would be something I would not like to have, because once I decided to use a toolbox tab I want it to stay open, I don't want the application to change it just to show me some information that could be served better in some other place

In my opinion, there are better ways to show messages / errors to the user, e.g. toasts / snackbars  (toast demo: https://www.primefaces.org/primevue/toast)

**Comment by sseppi** [comment]
@mrabans do you think that the actual way to manage the error messages in the beta is fine?

If so, I would suggest to close this issue and open a new on in case of specific needs.

**Comment by mrabans** [comment]
@sseppi it is fine for now, this might be enhanced in future.
