### ISSUE TITLE
As an Open data Hub Manager I want to monitor the errors of the Data Browser, to identify and solve the bugs as soon asp possible

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#185]
Tasks:
- [x] @gappc integrates in all API request the Origin header with the value `Databrowser2` => no need for Origin Header (see discussion below)
- [x] @RudiThoeni creates a monitoring dashboard for the Data Browser.

After this first iteration the error monitoring should be further investigated.

_Documentation_: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin

**Comment by gappc** [comment]
Hi @sseppi @RudiThoeni, we need to discuss if we want to use the `Origin` header or if we should use a custom header, e.g. `x-odh-client`. If we stick with the `Origin` header, we should use a value that conforms to the spec (see the link that points to the MDN documentation):

```
Origin: null
Origin: <scheme>://<hostname>
Origin: <scheme>://<hostname>:<port>
```

We should also distinguish between errors that happen because a request from the Databrowser to ODH failed (most of which can be tracked with the header mechanism mentioned in this issue) and client errors that can not be tracked because they are not related to a request. Please see my [comment](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/issues/89#issuecomment-1296288061) at issue #89 for further information.

**Comment by RudiThoeni** [comment]
no need for the origin header/parameter
It can be filtered by the referrer which the browser automatically passes to the api
![image](https://user-images.githubusercontent.com/30471361/198963682-ad8f1005-2850-4f99-8e94-8b5d1ad387a1.png)
Basic infos can be retrieved (path, queryparameters, http status, username etc...)
But as @gappc says for all errors that are not related to api calls the error is not shown......

The only drawback is that we currently are on the test api - test elastic.....  Because of the large amount our Testinstances are producing on the testserver we set the logging to max age 2 days here........

**Comment by RudiThoeni** [comment]
@RudiThoeni to check and provide the link of the dashboard (testing and produciton)

**Comment by RudiThoeni** [comment]
Dashboard for the production instance
https://logs.opendatahub.com/app/dashboards#/view/d7acb0e0-98a8-11ed-b69a-a15ab3b1f0cb

**Comment by sseppi** [comment]
@gappc as far as we can see the dashboard seems to work properly. 
I think you did everything on the DAta Browser side.

**Comment by gappc** [comment]
@sseppi the requests are filtered by the referrer header (see Rudis reply above). I think this ticket can be closed.
