### ISSUE TITLE
Add image placeholder in case no image is present or image con not be loaded.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#265]
Link to an example of not working image:
https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Weather/District

- [ ] @Mazzolintis will provide a placeholder image to be used everywhere there is an image that can't be loaded by the Data Browser
- [ ] @gappc will implement the usage of the placeholder image

**Comment by gappc** [comment]
@sseppi I think we should ask studiohug for a design / image to have nice visualization

**Comment by sseppi** [comment]
OK, I added also @pkritzinger as assignees so we can keep discussing it here and take a final decision at latest during the next sprint meeting

**Comment by Mazzolintis** [comment]
@sseppi @gappc --> here the link for the placehoder image https://prnt.sc/CSYs01AzGPkK What do you think? @gappc should I export an svg and send it to you?

**Comment by gappc** [comment]
@Mazzolintis could you please add the image to the MVP3 figma designs? There exists already a place with most icons, we could add it there. That way we have a central place for icons. Then I can export it as SVG by myself.

**Comment by gappc** [comment]
@Mazzolintis as you mentioned, the image is now part of the figma designs, thank you :+1:

**Comment by gappc** [comment]
The image placeholder is now included as of https://github.com/noi-techpark/it.bz.opendatahub.databrowser/commit/f1bd5ea628f7d8b23df2a02d36aeef61fd18dcd6

There remains one issue: in table view, the placeholder image is not centered. This is due to the way table cells work.

There are only a few ways to vertically center the content of table cells and only one works properly, using `vertical-align` on the table cell, but that definition can not be applied to all table cells, as it would look odd for most data.

@sseppi: we need to discuss if centering the placeholder image in table cells is really an issue. If it is, we need to find a way to fix the problem; otherwise, we could close this issue.

**Comment by Mazzolintis** [comment]
Hello @gappc  I have seen that you have only included the icon. I would also take the whole gray box, then we never have the problem with "centering"... or am I misunderstanding something here? Maybe we can talk about the topic tomorrow :)

**Comment by sseppi** [comment]
During the meeting we decided to use for the position of the "no image" icon the same logic of all other images.

We will keep the icon in the middle top of the cell.
