### ISSUE TITLE
Empty table/search message improvement

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#285]
As reported in the screenshot below, in case of empty table or empty result of a searc/filter, there is a generic message lke **No data**.

![Schermata da 2023-01-31 11-31-10](https://user-images.githubusercontent.com/7909989/215736891-5e455e3f-e110-4aed-8d3f-3bffaeea9261.png)

Opening the following link there is an example of it:
https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Article?idlist=1). 

For the next iteration, it would be good to indicate to the user that no results were found and to give a hint on what to do next.

**Comment by gappc** [comment]
Proposal by @pkritzinger (see #275)

"We could not find any data matching to your search request.
Our suggestions:

1. Check for typos in your search request.
2. Try to insert other terms."

**Comment by gappc** [comment]
@pkritzinger, @sseppi: in my opinion, the sentence is overly specific about searches:

- what if a user sets filters in a way that no results remain?
- what if a dataset contains no data at all because the endpoint/dataset has (yet) no data to provide?
- what if a dataset contains no data because the user has not the right permission and the data is filtered on the backend (e.g. user has no permission for LTS data but all records are from LTS)?

I think the message being specific about searches would be misleading then (please be aware, that on the frontend we have only limited capabilities to detect what causes the result to be empty).

@pkritzinger, @Mazzolintis, @sseppi: what do you say? Would it be possible to show a more generic message?

**Comment by pkritzinger** [comment]
@gappc Damn - I mixed that up, sorry. I thought we needed a specific system feedback for the search.

Ok, will prepare a more generic one.

**Comment by gappc** [comment]
@pkritzinger perfect, thank you :+1:

**Comment by pkritzinger** [comment]
We would like to integrate an animation for this. Find the lottie-json-attached.
How to insert the lottie file: https://lottiefiles.com/blog/working-with-lottie/how-to-add-lottie-animation-in-web-page-html
[no-result-animation.zip](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/files/10881155/no-result-animation.zip)


You can find a preview of the animation itself in the design.

**Comment by sseppi** [comment]
@pkritzinger I wasn't able to find the preview in the design. Can you please send me the link to the irght Figma?

**Comment by pkritzinger** [comment]
@sseppi will share when it is ready - i was too quick with my comment here ;)

**Comment by sseppi** [comment]
In my point of view, for now we can implement as it is. But probably in future once we will implement more search and filter functionality we will need to review it in order to provide a more useful feedback to the user, maybe including also suggestions.

What do the other think?

**Comment by pkritzinger** [comment]
@sseppi fully agree with you, but if we start working on more specific messages, we need to discuss that with @gappc - see his input below:
>what if a user sets filters in a way that no results remain?
what if a dataset contains no data at all because the endpoint/dataset has (yet) no data to provide?
what if a dataset contains no data because the user has not the right permission and the data is filtered on the backend (e.g. user has no permission for LTS data but all records are from LTS)?
I think the message being specific about searches would be misleading then (please be aware, that on the frontend we have only limited capabilities to detect what causes the result to be empty).

**Comment by sseppi** [comment]
@pkritzinger In this iteration I would suggest to implement the solution you proposed and then discuss possible enhancements that consider also the comments of @gappc in the next iterations.

**Comment by gappc** [comment]
@pkritzinger, @Mazzolintis: never mind, I've converted the lottie file to SVG ;)

**Comment by gappc** [comment]
@sseppi, @mrabans, @pkritzinger: done as of d5e6371c0b4ff5b597817b7ff6f59d5b102a0e0a, you can take a look here: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Article?searchfilter=doesnotexist

Please note that I've slightly changed the text to "You were looking for data that does not exist!"

If it's ok, please close the issue

**Comment by sseppi** [comment]
Super! I closed this issue and, as agreed in the yesterday's meeting I created a dedicated issue (#325 ) to discuss if we need to create also more specific error messages also for other error types. 

in my point of view after a few month of testing with real users we will have more information that allow us to take a better decision.
