### ISSUE TITLE
Bug with the section menu bar of the shared view on mobile 

### ISSUE THREAD

**Issue by d3liaa** [noi-techpark/it.bz.opendatahub.databrowser#301]
When in mobile mode in the detail/edit view the menu bar above for the section disappears and reappears randomly when scrolling down.

**Comment by sseppi** [comment]
@d3liaa thank you for the issue you found. Can you please share with us the following additional information:
- which mobile phone did you use?
- which Operating System version dis you use?
- which browser did you tested?
- can you please add also a screenshot?

Thanks

**Comment by gappc** [comment]
@d3liaa, @sseppi: the fix is implemented and deployed to the TEST environment, e.g. see here: https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/Accommodation/5CEA544EE34639034F07B79D4AEEB603#main-data

If you watch that page on a mobile phone you should see that it works now as expected. Please check and let me know

**Comment by d3liaa** [comment]
I tested it (on mobile:safari and on pc: small screen view on chrome) and it works amazing now! Thank you!
