### ISSUE TITLE
As an Open Data Hub Data Browser visitor I want a back button in the Dataset Overview, to be able to go back to the list of all Data Sets.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#302]
During the testing some user weren't able to find a way to go back to the dataset list from the Dataset Overview.

A proposal could be to add in the Dataset Overview (screenshot below) a "Back to dataset list" button or link.

![Image](https://user-images.githubusercontent.com/7909989/220324979-5241570c-5678-4a66-9c5b-62af36342426.png)

**Comment by pkritzinger** [comment]
See proposal here: 
https://www.figma.com/file/DmuP6Dbv5LzkCNOXrDnWIL/2023?node-id=9%3A2931&t=kZTFyhuvfbX1sTJ8-1

**Comment by sseppi** [comment]
@pkritzinger thank you for the proposal!

What about adding the link also on the top of the page? As for example over the Description of the dataset?
In this way the user could always go back without scrolling.

**Comment by gappc** [comment]
@pkritzinger: I have the same feeling as @sseppi. When a looked at the design it took me quite some time to find the back-link.

The use-case for a (additional?) back-link somewhere on top would be:

- I open the details page because of a link / bookmark / whatever
- I want an overview of the datasets

In that use-case (happened to me quite often), either I know where to look for a back-link or it takes me some time to figure it out / I'm stuck or I take the route via the home page. Either way, having a back-link - or some other navigation to the dataset overview - would solve that case.

**Comment by pkritzinger** [comment]
@sseppi @gappc ok, see your points. Regarding the different inputs we should maybe think of an overall "header"-module that also integrates a backnavigation, example (this is a blog article and completely different from a content-point of view but it has the same logic, i.e. overview page and detail page): 
![image](https://user-images.githubusercontent.com/92454516/225670180-1ab4d4c4-6305-4981-8ff4-be494ee9dedb.png)

Proposal for the next steps:

- [ ] Define added information per detail page
- [ ] Rework "Header" module for detail page including back-navigation
- [ ] I would suggest to implement the back-button at the bottom for the moment being since we will not change it very soon.

**Comment by sseppi** [comment]
@Mazzolintis @gappc the updated design is fine for me!

**Comment by gappc** [comment]
Implemented as of #0026bb065548da89667784727e1339bf8d0680b5, e.g. see here: https://databrowser.opendatahub.testingmachine.eu/dataset-overview/it.bz.opendatahub.accommodation

@sseppi @pkritzinger if it's ok, please close this issue

**Comment by sseppi** [comment]
Fine also for me!
