### ISSUE TITLE
As an Open Data Hub manager I wnat that opening hours are managed in the Data Browser, to allow the users to see and edit the opening hours.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#339]
The component to show / edit Opening Hours / Seasons is implemented and deployed to the TEST environment. The component is relevant for the following datasets (see example links):

- Article:
https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/Article/23FCAF4A-35C1-09BE-B013-02F16E7CA5E1#season-opening-hours

- Gastronomy:
https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/Gastronomy/GASTRO2657B7CBCB85380B253D2FBE28AF100E#season-opening-hours

- ODHActivityPoi:
https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/ODHActivityPoi/smgpoi2379cd9828158d300cf0c677ef6431fa#season-opening-hours

- SkiArea:
https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/SkiArea/SKI6C7D174390D44D0ABC1C9105F8C37C5E#season-opening-hours

This issue has been created to collect bugs and possible enhancements.

**Comment by pkritzinger** [comment]
My Feedback:
- Pleaes insert Name-Attribute within Season-tile: https://prnt.sc/bs3ycU4mNSWv
- Please integrate the timecode dynamically in the title of the tile of opening hours: https://prnt.sc/M0-MB1Rnip5l
- Please add edit (anchor to respective opening hour) and delete-icon to tile - as done in the design: https://prnt.sc/CFvtrbgyZbPf
- Remove information since it has nothing to do with the opening hour: https://prnt.sc/FfDhyCfe7HBI
- Please check border of days, should be the same as border of opening hours, i.e. 1px, #E3E4E7 (https://prnt.sc/GB10ySoTVz77)
- Width of container for input fields is much lower than width of fields that summarize inserted data (https://prnt.sc/5eHZ1prV3u6y) Is there anything we can optimize about?

**Comment by sseppi** [comment]
@pkritzinger thank you for the inputs! We will discuss it tomorrow in the sprint meeting

**Comment by sseppi** [comment]
During the sprint meeting it has been decided to try to implement all feedback provided by Paul.

In case the edit button in the Opening Hous box is too complex to be implemented, a dedicated issue wull be opened by @gappc .

**Comment by sseppi** [comment]
All changes has been implemented, we keep it in review for the next iteration and, if no other issue will be found, this issue will be closed at the next sprint.
