### ISSUE TITLE
The “Add a record” does not work from Table View and Detail View

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#340]
As explained by Chiara for some datasets, the `Add a record` button doesn't work from the Table View, the Raw View and the Detail View.

More details are available in the slide 2, 3, 4 and 5 of the presentation at the following link:
https://docs.google.com/presentation/d/1rHV6uue1r8hk_tQD2Q0KFRPI6w8alPld9n6mUnnPSdE/edit?usp=sharing

**Comment by gappc** [comment]
@sseppi yes, now it works :+1:

**Comment by gappc** [comment]
@sseppi there was a bug that was fixed in 51b3cc60, the "Add a record" button was shown even if no NewView existed.

Below you find the new checks. The "Add a record" button will only be displayed if all of them are met:

- the user has the permission to create new records for the current dataset
- there is a dedicated NewView config to add a new record for the current dataset
- the view config is embedded and not generated

Since we have never discussed how adding a new record should behave (what is there at the moment is just some proof of concept on my behalf), maybe this issue can be used as a start to get that feature implemented fully.

In essence the idea is to have a trimmed-down version of the EditView of a dataset with only the fields necessary to add a new entry. Note that it is also possible and feasible to just reuse the EditView to add a new dataset, but for some EditViews the required fields are distributed among different categories, which makes adding a new record clumsy.

**Comment by sseppi** [comment]
During the sprint meeting we decided to reuse the Edit View to create a new record.

In case of need we will the  decide how to improve the "Add new record" functionality on top of the feedback provided by the users.

**Comment by d3liaa** [comment]
Datasets were the new record is implemented:
- [ ]  Ski Area
- [ ]  Ski Region
- [ ]  Tourism Association List
- [ ]  Region
- [ ]  Municipality
- [ ]  District
- [ ]  Experience Area List
- [ ]  ActivitiesPOIs
- [ ]  Accomodations
- [ ]  Events
- [ ]  Events Eurac NOI
- [ ]  Venues
- [ ]  Articles
- [ ]  Webcams
- [ ]  Gastronomy
- [ ]  Wine awards
- [ ]  Snow Report
- [ ]  Measuring Point
~~Weather~~
~~WeatherHistory~~
~~Weather District~~
~~Weather in Realtime~~
~~Meta Region~~

**Comment by sseppi** [comment]
Top!

I reviewd the list with Rudi that agrees.

Thank you @d3liaa

**Comment by gappc** [comment]
@sseppi @d3liaa I think the config changes have still to be done, is that correct?

**Comment by d3liaa** [comment]
I did them I only have to push it. I’ll do it ASAP
Il giorno mar 9 mag 2023 alle 15:46 gappc ***@***.***> ha
scritto:

**Comment by gappc** [comment]
@d3liaa @sseppi PR is merged as of fce9fd5e92b889d1a8498365b75707dc77db4601, please check and close the ticket if ok.
