### ISSUE TITLE
As an Open Data Hub Data Browser user I want a guideline on how the search and filters works, to easily find the data I'm looking for

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#368]
After an internal discussion we decided to put for the moment collect How To of the Data Browser the a wiki section of the repository of the Data Browser:
https://github.com/noi-techpark/it.bz.opendatahub.databrowser/wiki
I created the home page and the page for the How To for the filter and search functionality:
https://github.com/noi-techpark/it.bz.opendatahub.databrowser/wiki/How-To-Filter-and-Search

The next steps of this issue are:
- [x] @pkritzinger and @Mazzolintis will provide a proposal for the content to be included in this how to section;
- [x] @d3liaa will create the content (maybe also short how to video tutorials) and show them to the team
- [x] @d3liaa will input the content in the dedicated wiki page

In further iterations the team will consider if it would be better to continue to use the wiki page in git to collect the how to or create a dedicated section in the Open Data Hub Data Browser itself.

**Comment by pkritzinger** [comment]
### Structure for Usage of filters in wiki:
**Access and purpose:** Describe that the filters can be accessed in each column of the table view in order to search and quickly find specific data.
**Extent of functionality:** Describe the feature-extent of the filters, i.e. That the variable/ column the user wants to filter for can be selected, the respective operator can be selected and the filter value can be inserted (integrate screenshot). Let users know that filters are always combined with a &-condition and provide an example.
**Limitations of filters:** Describe, when filters work (i.e. when the correct filter term is inserted) and when they do not work (i.e. when a value is inserted that does not consider the value provided by the API). --> Let users know, where they can find additional information on which values are transmitted by the API and provide a link to that section.
**Potential issues and challenges:** Describe potential issues and challenges the user could face, e.g.: Filters in combination with search do not work.
**Support & feedback:** Provide contact information or links to support resources. Encourage users to provide feedback/ potentials for optimization on the filter functionality.

**Comment by d3liaa** [comment]
@pkritzinger @sseppi you can view the updated documentation here https://github.com/noi-techpark/it.bz.opendatahub.databrowser/wiki/How-To-Filter-and-Search
If i missed something or want something changed , let me know :)

**Comment by gappc** [comment]
@d3liaa thank you for your work, looks good to me :+1: 

@delia @sseppi @pkritzinger I have now added the "Info" icons and popovers to search and filters in the table toolbox (see image below). Example: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Accommodation

Please check if it works as intended.

![image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/5732768/fb304a2e-0389-4716-b3f0-73c60a90d712)

**Comment by pkritzinger** [comment]
Hi @d3liaa 
Thank you very much for the wiki-documentation, it looks supergood - I like it!
Some feedbacks:
- Filters can also be accessed via the arrow at the righthand side (Screenshot: https://prnt.sc/AFSiUEkP4X6Y). Maybe we can add this info?
- I would use the term "basic search filter". This could lead to misunderstandings in combination with the description of "normal filters". Suggestion: I would simply name it "basic search"
- I am not sure if this description applies to the basic search "It searches for an exact match or _even partial matches_ within the text." Or rather: what is meant with partial matches?

**Comment by d3liaa** [comment]
Hi @pkritzinger :)
thank you for the feedback!
I implemented the changes.
By partial matches, I mean that you don't have to have the complete text to find a match.
For example, if you have the title:  "Titolo di un film" 
if you search : "film", "f", "titolo", "un" etc.. It will show up in the search 
instead in the filter to have a match you would have to input: "Titolo di un film" or it won't shop up.
Hopefully its clearer now :)

**Comment by pkritzinger** [comment]
Thanks @d3liaa it's crystal clear now ;)

**Comment by pkritzinger** [comment]
@gappc regarding the info-icon and popover: Could you pls. add the "x" to the popover? Especially on mobile devices it may be hard to close the popover again. 
Further, Access to Hotjar lies in the foreground of the popover. Could we pls. bring the popover to the front?

**Comment by sseppi** [comment]
@gappc during the meeting has been decided to put the "x" on all popover.

**Comment by gappc** [comment]
@sseppi @pkritzinger done as of 1cec6a64c4ec1ba4c6857c21ee1ae56474eb2ced

You can take a look at it e.g. here: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Article

If the implementation and search / filter guideline are ok, then please close this issue.

**Comment by sseppi** [comment]
@gappc If I got it right, we can move the issue in the review lane?

**Comment by sseppi** [comment]
For the moment the documentation about filters and search seems to be complete.
In case of need to improve documentation a new issue will be opened.
