### ISSUE TITLE
As a Data Browser user I want that every column contains only one value, to be able to activate the sorting and the filtering on each column

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#388]
As discussed in the yesterday's meeting we decided to put in each column maximum one value.

For example the ``Location`` column should be divided in two different columns ``Reagion`` and ``Municipality``
![Schermata da 2023-06-07 20-39-40](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/de466cda-1445-439a-86fa-366e83b06f21)

We need to check the configuration of all table view and avoid to have multiple values like the one in the example.

**Comment by gappc** [comment]
@sseppi done as of 066c617d22382786cc99762921a975f0a531d216

You can take a look at it e.g. here: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Accommodation

Please note that there remains one Table View with a column that is not split yet, because it's a column that shows GPS coordinates: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Weather/Realtime. Should we split that column, too? Note that that column may show data for `lat`, `lng`, `altitude` and `altitude unit`.

**Comment by sseppi** [comment]
@gappc @pkritzinger 

I would say, that we should split the ``GPS`` column into ``Latitude`` and ``Longitude`` to use always the same logic.
Tomorrow during the Sprint Meeting we can take the final decision.

**Comment by sseppi** [comment]
We decided during the meeting to create a column for each value: Latitude, Longitude, Altitude. For the moment we decided to not show the unit of measurement.

The unit of measurement could be evaluated in future iterations while we integrate sensor data.

**Comment by sseppi** [comment]
@ila131 can you please change the configuration to render in the Table View the GPS colums in 3: Latitude, Longitude and Altitude.

**Comment by ila131** [comment]
> @ila131 can you please change the configuration to render in the Table View the GPS colums in 3: Latitude, Longitude and Altitude.

Hey @sseppi I just opened a PR https://github.com/noi-techpark/it.bz.opendatahub.databrowser/pull/404

Have a nice day,
Ilaria

**Comment by gappc** [comment]
Done as of ebb0366567ca260eec35ea6d46b02807730b0380
