### ISSUE TITLE
As a Data Browser user I want an updated version of the file name changer component, to easily CRUD the file name in all languages in one time.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#438]
In the meeting of the 24th October we decided to keep the actual implemented version with the following changes:

-  user sees always all 8 languages (also the deactivated one);
- if a user adds a Document Language in one new language, the checkbox will be automatically activated;
- if a user deletes the File Name in one language, the checkbox will be automatically deactivated;
- if a user deselects the checkbox of one language, the file name in the deselected language will be deleted at the next save;
- if a user deselects all languages, the user will be notified with a text-box that provides the following option:
  - delete also the file;
  - keep the file without any file name;
  - back (goes back to the file name dialog to reactivate one or more languages).

**NOTE:**
During the discussion it emerged that this component could be generalized to allow to easily make changes to fields that have a list of values (e.g. what does happen if in the future we add a lot of new languages?). The team decided to bring in production the actual version with the smallest changes as possible, to collect feedback from the users as soon as possible and with the little effort as possible. In any case, we should keep in mind that maybe it could be worth to consider a generalization of this component. (@mrabans please integrate this note or create a dedicated discussion if you think is necessary)

@pkritzinger can you please share the link to the updated version of the design?

**Comment by pkritzinger** [comment]
@sseppi here's the updated version for file upload:
https://www.figma.com/file/DmuP6Dbv5LzkCNOXrDnWIL/2023?type=design&node-id=1219%3A1707&mode=design&t=trlPGbjxC3ZpKG2J-1

**Comment by sseppi** [comment]
@MatteoBiasi I think we are now ready for the estimation for the implementation also of this issue.

**Comment by RudiThoeni** [comment]
The latest PR is now on Test, i tested and what i noticed:

-On **insert** Adding a file and using "Save & next" calls the Save Method of the whole Data is this intentional? on edit it is working as expected
-On editing the Single Files ( i have 2 files inserted)
![image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/30471361/64cbf438-8c91-4bff-b134-46c0cd7d2b24)
the "Update language settings" seems not to show the right data, it shows the same data on each file (Always the last inserted)
here for file 1 (where i inserted it + en)
![image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/30471361/5deccbc5-266c-488a-bf63-94868f0eab3a)
and here for file 2 (where i only inserted en)
![image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/30471361/e40f54cf-0514-47e4-b334-0fe1e7db9bd6)

@sseppi please also test but as far i can see we have still some bugs here

**Comment by sseppi** [comment]
@MatteoBiasi I got the same problems as Rudi reported, please test deeply the all fetures, fix the bugs and open a new PR once all bugs are solved.

**Comment by sseppi** [comment]
It seems that now everything is working fine. As agreed this morning I ask @MatteoBiasi to deeply test the Save functionality considering also the problems mentioned during the call.

Before to close the issue:
@pkritzinger a better and clearer text for the language activator popup
@MatteoBiasi will change the texts and make a new PR

**Comment by pkritzinger** [comment]
@sseppi @MatteoBiasi 
Here's a suggestion for the optimized text:
- Headline: Set document names.
- Subheadline: Define a document name for each language. By giving the document a name, you make it available in the respective language. 
- Primary Button: Ok
- Secondary Button: Cancel

**Comment by sseppi** [comment]
@pkritzinger the proposal is fine for me.

@MatteoBiasi I think you can implement the chnges.

**Comment by MatteoBiasi** [comment]
@sseppi texts updated. Here's the PR: https://github.com/noi-techpark/it.bz.opendatahub.databrowser/pull/530
