### ISSUE TITLE
Difference between detail/edit view and Add a new record view

### ISSUE THREAD

**Issue by d3liaa** [noi-techpark/it.bz.opendatahub.databrowser#439]
The add a record configuration is different from the detail / edit view. 
The add a record view should be the same as the edit but only blank. 
I noticed this for example in the article dataset:
As is visible in the screenshots below there are two fields that should not be present in the Main Data and the published on is completely missing from the configuration.
![article-ss](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/101118017/3b2eb14e-e6ef-4ad6-bfdf-144b1744d1cd)
![article-ss1](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/101118017/d508ab71-55cb-43af-b9c0-bb8e9407458f)

@dulvui since you have to touch the code, can you please remove the beta badge hard-coded and apply it in a parametric manner. The goal is to have the following behaviour:
- databrowser.opendatahub.testingmachine.eu --> Testing badge
- v2-beta.databrowser.opendatahub.com --> Beta badge
- databrowser.opendatahub.com --> No badge

**Comment by gappc** [comment]
@d3liaa @sseppi yes you are right with your observation.

I checked, and the only two datasets with dedicated configuration for add-a-new-record are [Articles](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/development/databrowser/src/config/tourism/article/article.newView.ts) and [PublishedOn](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/development/databrowser/src/config/tourism/publishedOn/publishedOn.newView.ts).

If @d3liaa 's assumption is correct (new view should be the same as edit / detail view), the fix is as follows:

- remove the files mentioned above
- update the respective [articles.views.ts](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/development/databrowser/src/config/tourism/publishedOn/publishedOn.views.ts) and [publishedOn.views.ts](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/development/databrowser/src/config/tourism/publishedOn/publishedOn.views.ts) files

This change would be a good starter / project-introduction issue if anyone is interested in.

**Comment by sseppi** [comment]
@pkritzinger @Mazzolintis In my point of view the "New record" and the "Edit" should be the same for a Dataset. The only difference between the two is that the "New record" is completely empty.

If you don't see any contra, I would suggest to plan to do the changes proposed by Chrsitian.

@gappc do you think that this activity could be a good starting point for Simon to start the introduction to the new Data Browser?

**Comment by gappc** [comment]
@sseppi yes, it would be a good first issue for Simon :+1:

**Comment by dulvui** [comment]
@sseppi Both issues are now fixed and ready to be merged as PR

**Comment by sseppi** [comment]
@dulvui thank you for the changes, did you already do the PR?

@gappc shall we organize a meeting with Simon to do the review together and coordinate us for future PRs?

**Comment by dulvui** [comment]
@sseppi Yes PR are ready for review

**Comment by gappc** [comment]
@sseppi @dulvui i already merged the PR for this issue (#446). If you want we can schedule a meeting for the other PR (#445) or we can just merge it.

**Comment by sseppi** [comment]
@gappc you can just merge the PR #445, we will define after a coordination meeting with Simon

**Comment by gappc** [comment]
@sseppi @dulvui merge was done 👍

**Comment by sseppi** [comment]
Now it seems to be everything fine!
