### ISSUE TITLE
Bug: First publisher added does not work properly

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#447]
- **Device**: Desktop 
- **Operating System:** Ubuntu
- **Browser:** insert the Chrome, Brave and Firefox
- **Problem Description:**
As data browser logged user if I want to add a new publisher to a record, the first time I click on the `Add new publisher` button, it appears only the link to the Drin Publisher without any possibility to change the added publisher.
If you try to add a second time the behavior is correct.
Steps to reproduce the bug:
  1. Login into the data browser with a user that has write rights;
  2. Open a record of a dataset that has Publisher configured;
  3. Click on `Add new publisher`
  4. Click on `Add new publisher` another time

- **Expected behavior:**
Also when the user clicks on the `Add new publisher` button the first time the component should add a new empty line to the Publisher table. This new line should contain in the column `Name` a Dropdown menu that allows the user to select the Publisher he wants to add.

- **Screenshots:**
Screenshot of the empty Publisher table:

![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/d38ed6cf-1b93-4422-9f2b-90642d7fde58)

Screenshot of the Publisher table after clicking the `Add new publisher` the first time:

![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/9acf4198-254f-4c52-a9d1-a33fbdb3489d)

Screenshot of the Publisher table after clicking the `Add new publisher` the second time:

![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/c6dc8cc6-e12b-4edc-a00b-31d7f1ee3797)

**Comment by sseppi** [comment]
@gappc can you please have a look at this bug, so we can discuss it at the next refinement meeting?

**Comment by sseppi** [comment]
Same issue also noted in the Category and Data Provider table of the "Dataset Information" dataset

https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/MetaData/01df71d7-7d48-491d-bcd2-e6e6d012e626

**Comment by gappc** [comment]
@sseppi that's a strange issue, it doesn't happen with the latest commit of the development branch (849621b2307efd44841d633b659dd4672d7461cb) when started locally. For example, if I open http://localhost:3000/dataset/edit/tourism/v1/ODHActivityPoi/dss_187043 and try to add a new publisher, it works as expected.

On the other side, if I try to do the same on https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/ODHActivityPoi/dss_187043, then an error message appears (see below) and the behavior is the same as you mentioned. Is the same error message shown to you? All I can say is that the code tries to access a value that doesn't exist. Maybe that bug is already fixed in a current version?

![image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/5732768/de26481e-2a23-4c99-b165-3956c680eb14)

It seems that the current development version and the version deployed to https://databrowser.opendatahub.testingmachine.eu differ. After the last modifications to the deployment configs, I'm not sure which version / commit is deployed to which URL. I'm also not sure when the deployments run. Could you please check with @dulvui?

In order to reduce friction and to simplify information gathering in case of errors I propose the following updates to the project:

-  improve the documentation, e.g. by putting a `deployment.md` in the projects `doc` folder that describes the deployments and the triggers that start the deployments
- add a mechanism to get information about the commit that was used to build and deploy. It would be very nice if we had e.g. a link / button / page inside the Data Browser where we could get such information

**Comment by sseppi** [comment]
@gappc will you investigate where the problem is, or shall we ask a-crea that made the PR #432 ?

**Comment by dulvui** [comment]
@sseppi @a-crea the PR is now merged and ready for testing on https://databrowser.opendatahub.testingmachine.eu

**Comment by sseppi** [comment]
Now the functionality seems to work properly.
