### ISSUE TITLE
Is "Quick view" description in doc / overview.md still valid?

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/it.bz.opendatahub.databrowser#552]
Should this paragraph been removed? Do we still have the "Quick view"?

- **Quick view:** The quick view is a user-friendly interface that provides a concise and summary-based overview of a record, highlighting the most important attributes. It aims to present key information in a visually appealing and easily digestible format.

https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/development/doc/overview.md#visualization

**Comment by gappc** [comment]
@ohnewein @sseppi @mrabans technically, we still have the Quick view and it is used for datasets of type `ODHActivityPoi`. 

You can see that there is a button on the left of ODHActivityPoi table view that opens the Quick view (https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/ODHActivityPoi).

![image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/5732768/6affc931-a3f2-4667-b587-abdf35834074)

Unfortunately, there seems to be a fresh bug in the Quick view, because it fails to show data when opened (e.g. https://databrowser.opendatahub.testingmachine.eu/dataset/quick/tourism/v1/ODHActivityPoi/smgpoifad01289740e1d2f58dc1aa29288bb33). The bug seems related to the Leaflet library that is used to show maps. I didn't take a look at it yet, because I'm not sure if the Quick view remains in place.

We should decide if we want to keep the Quick view. If it turns out that we want to keep it, we should plan what to do with this feature, because at the moment it is half-complete (ODHActivityPoi only). If it turns out that we don't need the Quick view, then I think it would be best to remove the feature and stuff related to it.

**Comment by ohnewein** [comment]
My suggestion would be to reduce complexity. If there are no users requesting it, I would remove it.

**Comment by sseppi** [comment]
@gappc 

> My suggestion would be to reduce complexity. If there are no users requesting it, I would remove it.

I agree with Patrick, let remove it. If users will ask for it, we will fix the bug and publish it again.

**Comment by gappc** [comment]
@ohnewein @sseppi PR #559 removes the Quick View

**Comment by sseppi** [comment]
> @ohnewein @sseppi PR #559 removes the Quick View

@gappc Perfect! Thank you! Is the PR ready to be merged?

**Comment by gappc** [comment]
@sseppi yes it is ready

**Comment by gappc** [comment]
@ohnewein @sseppi @RudiThoeni the Quick View was removed as of commit 339544cda98d6ddb994c40a2eae3651f630bd229

If it's ok with you, we could close this issue.

**Comment by sseppi** [comment]
@RudiThoeni did you deploy this update also on production?

**Comment by RudiThoeni** [comment]
@sseppi no i wanted to do a production deploy today
