### ISSUE TITLE
ODH data structure consistency

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#85]
- most endpoints in ODH tourism API provide an `Id` property (uppercase `I`, followed by lowercase `d`) for each data entry, but Rudi told us that there is an endpoint that uses `id` (both chars lowercase) as property, if I (Gapp Christian) remember correctly it was for an AlpineBits endpoint and the reason was, that `Id` was already used => exceptions like this complicate the whole implementation
  - are there more exceptions like this? => talk to Rudi
- The tourism API uses a different pagination type than the mobility API (page based vs. offset based)

**Comment by sseppi** [comment]
@gappc I think that this issue whould be extended also to the mobility domain, since is it will be integrated as well in the data browser

**Comment by sseppi** [comment]
@gappc I think some of the points are discused in the issue #180 

Is this issue still needed or shall we close it and open more specific once specific cases are detected and when we will integrate also the mobility data?

**Comment by gappc** [comment]
@sseppi the problem with different cases for the ID property (upper- / lowercase) still exists. Examples:

- [Accommodation](https://tourism.opendatahub.bz.it/swagger/index.html#/Accommodation/AccommodationList) and most other datasets use `Id`
- [Weather Realtime](https://tourism.opendatahub.bz.it/swagger/index.html#/Weather/get_v1_Weather_Realtime) uses `id`, same goes for [Venue](https://tourism.opendatahub.bz.it/swagger/index.html#/Venue/get_v1_Venue)

It is not as big of a problem, because I implemented a simple check which one to use (see [the code](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/b05ccd9c24ecedc5488d09cfcac09ab548390bf0/databrowser/src/domain/datasets/tableView/TableContent.vue#L129)), but it would definitely be nice if the API used consistent casing.

**Comment by sseppi** [comment]
@RudiThoeni would it be possible to add also the ID to the issue #180 or will it be to difficult?
